### ISSUE TITLE
Lab1: Peer review by Krzysztof Kleist s296450

### ISSUE THREAD

**Issue by KrzysztofKleist** [mttmtt31/compIntelligence_2022#1]
It's good and productive that you implemented the new ```TupleSet()``` class to make your approach more individual. Also it's well described in ```README.md``` file.
Unfortunately you didn't provide the solution in the notebook, it could be way more readable, there are a lot of useful comments though.
Another good thing is the check if the problem is solvable.
Unfortunatelly you managed to solve only **Breadth-first search** but your solution can be considered as complete because you also managed to provide solutions for N > 20 what was problematic.

**Comment by mttmtt31** [comment]
Thanks for your feedback!

We did not think of providing a notebook solution for the sole reason that their usage is not as integrated into Github as with the normal Python scripts (allowing you to jump from one script to the other, for example).
