### ISSUE TITLE
Review #1 Lab1

### ISSUE THREAD

**Issue by vmask25** [mttmtt31/compIntelligence_2022#2]
The main function is well structured, you can clearly see the attention to details of making it the most parametrizable and modular as possible, open to the addition of new algorithms other than the Breadth First.

Great idea to check if the problem is solvable! With the seed 42 and the given N's to try it never happens, but I think with other seeds it could.

Considering that I'm new to Python, it has been a bit difficult to me at the beginning to read and understand the flow of the code with the nested objects inside other objects, the SolvedProblem object has a nested object called Problem which has in its turn a property P that represents the problem's tuples, passing 3 times the two parameters N and seed deep through nested objects/functions to reach another "problem" function that returns the actual tuples. Anyway, this made the solution very well structured and there are useful comments that helped me!

The line 50 in solution.py:
initial_state = random.choice(max(self.problem.P, key = len)) 
is not clear to me.
Why do you pick as initial state one of the numbers inside the longest list?
Maybe the "max" is an error? Because the initial state I think should be a valid list and not a single element of one of the possible lists. Or maybe you wanted to select the longest list to start from the "max covering" one and so the random was supposed to choose one between the multiple longest lists?
(Incidentally at least with N=5 it's not a problem because the selected element as initial state was also one of the possible lists)

In the possible actions calculation are repeated multiple times the same tuples/lists, but me and my group didn't consider too the possibility of reducing the search space deleting duplicates as the Professor did in his solution.

In the result function of the TupleSet there is always the return of a new tuple as new state, combining in a bigger tuple the current tuple solution with another tuple, generating a lot of nested tuples instead of having a more "linear" list/set of tuples that represent the lists of the solution (and this could have generated the problem of counting the cost of the solution).
Maybe it was done on purpose to make everything work with the hashable problem, I don't know and please correct me if I'm missing something.

The compute_cost function is not computing the right cost I think. If I’m not wrong, the cost should be the number of numbers in the solution, independently from how they are grouped in lists.
So the PriorityQueue is biased by this calculation I think, with some slight changes it should work fine.

There isn't a check that the candidate numbers aren't already covered, and this leads to the possible insertion of a list that covers exactly the same numbers that have been already covered by lists already in the solution state (this can be caused by the "new_state not in self.state_cost" that doesn't check the actual presence of the numbers in the current state, but only the presence of the candidate list in the already added lists).

In the end the cost you print is not the actual requested cost to be minimized, but despite these little problems you found a solution up to N=500 so great job! 
As I said your solution is very structured and I'm new to Python so I could have missed something or written something wrong here, please feel free to correct me and discuss further.

**Comment by mttmtt31** [comment]
Thank you for your feedback!

> Why do you pick as initial state one of the numbers inside the longest list?

I need to double-check this, but that line of code does not pick out one number in the longest list, but picks out (at random) one of the longest lists, so that we are starting somehow closer to the final solution that we would have if picking out a shorter list. 

> In the result function of the TupleSet there is always the return of a new tuple as new state, combining in a bigger tuple the current tuple solution with another tuple, generating a lot of nested tuples instead of having a more "linear" list/set of tuples that represent the lists of the solution

We opted for this option so that it was possible to retrieve the "history" of the additions, but as you said handling with nested tuples was a bit tricky. If we were to do it from scratch, we'd probably go with a more linear choice, as you correctly pointed out.

> The compute_cost function is not computing the right cost I think. If I’m not wrong, the cost should be the number of numbers in the solution, independently from how they are grouped in lists.

`sum(candidate.count.values())` We are actually summing how those numbers are grouped in the list so that we indeed obtain the number of numbers in the solution.

> There isn't a check that the candidate numbers aren't already covered, and this leads to the possible insertion of a list that covers exactly the same numbers that have been already covered by lists already in the solution state

This is actually performed in the `possible_actions` function, where we checked which are the possible actions given a candidate solution.
