### ISSUE TITLE
Review Lab2 - Krzysztof Kleist

### ISSUE THREAD

**Issue by KrzysztofKleist** [mttmtt31/compIntelligence_2022#3]
## Review Lab2

The solution provided by you is very clearly explained in README.md.
You enabled two ways to manage the addition of offspring that lets us explore your solution more. The code is commented and quite clear, it's very hard to find any proper mistakes.
Also the results are satisfactory, especially for the numbers of N <= 100. Later you even improved it for the N = 500 and 1000 and the results there are comparable to the best results presented in the class.

The only "mistake" that you made is that, I think, you forgot to upload the last two images for README.md, but it's not really a mistake :)

Good job!

**Comment by mttmtt31** [comment]
Thank you for your feedback! We are glad you liked it.

You're right, the links to the pictures are broken. I will fix it :)

Cheers
